# ===========================================
# 🚀 Vidyamrit Full Stack Deployment Workflow
# ===========================================

name: Deploy Full Stack App to EC2

on:
  push:
    branches:
      - main

env:
  # Frontend ENV
  VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
  VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
  VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
  VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
  VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
  VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
  VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}

  # Backend ENV
  PORT: ${{ secrets.PORT }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  FIREBASE_SERVICE_ACCOUNT_KEY_PATH: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_PATH }}
  MAIL_USER: ${{ secrets.MAIL_USER }}
  MAIL_PASS: ${{ secrets.MAIL_PASS }}
  CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  LOGGER_PATH: ${{ secrets.LOGGER_PATH }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # ✅ Frontend
      - name: Install frontend deps
        working-directory: ./pwa
        run: npm ci

      - name: Create frontend .env
        working-directory: ./pwa
        run: |
          cat <<EOF > .env
          VITE_BACKEND_URL=${VITE_BACKEND_URL}
          VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
          VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
          VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
          VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
          VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
          VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
          EOF

      - name: Build frontend
        working-directory: ./pwa
        run: npm run build

      # ✅ Backend
      - name: Install backend deps (with production)
        working-directory: ./backend
        run: npm install

      - name: Create backend .env
        working-directory: ./backend
        run: |
          cat <<EOF > .env
          PORT=${PORT}
          MONGO_URI=${MONGO_URI}
          FIREBASE_SERVICE_ACCOUNT_KEY_PATH=${FIREBASE_SERVICE_ACCOUNT_KEY_PATH}
          MAIL_USER=${MAIL_USER}
          MAIL_PASS=${MAIL_PASS}
          CORS_ORIGIN=${CORS_ORIGIN}
          OPENAI_API_KEY=${OPENAI_API_KEY}
          LOGGER_PATH=${LOGGER_PATH}
          EOF

      - name: Build backend
        working-directory: ./backend
        run: npm run build

      # ✅ Prepare Deployment Folder
      - name: Prepare deployment folder
        run: |
          mkdir -p deploy/frontend
          mkdir -p deploy/backend

          cp -r pwa/dist/* deploy/frontend/

          cp -r backend/dist deploy/backend/dist
          cp -r backend/node_modules deploy/backend/node_modules
          cp backend/package.json deploy/backend/

          cp backend/firebaseServiceAccountKey.json deploy/backend/ || echo "Will symlink on server"

      # ✅ Upload to EC2
      - name: Upload to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "deploy/"
          target: "/home/ubuntu/vidyamrit_prod/"
          overwrite: true

      # ✅ Deploy on EC2
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            cd /home/ubuntu/vidyamrit_prod/deploy

            echo "🔥 Creating backend env"
            cat <<EOF > backend/.env
            PORT=${{ secrets.PORT }}
            MONGO_URI=${{ secrets.MONGO_URI }}
            FIREBASE_SERVICE_ACCOUNT_KEY_PATH=/home/ubuntu/vidyamrit_prod/deploy/backend/firebaseServiceAccountKey.json
            MAIL_USER=${{ secrets.MAIL_USER }}
            MAIL_PASS=${{ secrets.MAIL_PASS }}
            CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            LOGGER_PATH=${{ secrets.LOGGER_PATH }}
            EOF

            echo "🔑 Linking Firebase key"
            ln -sf /home/ubuntu/secrets/firebaseServiceAccountKey.json /home/ubuntu/vidyamrit_prod/deploy/backend/firebaseServiceAccountKey.json

            echo "🚀 Starting backend via PM2"
            pm2 restart backend-app || pm2 start /home/ubuntu/vidyamrit_prod/deploy/backend/dist/index.js --name backend-app
            pm2 save

            echo "🌍 Deploying Frontend"
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/vidyamrit_prod/deploy/frontend/* /var/www/html/

            echo "✅ Deployment complete"
            pm2 status backend-app
